# Generated by Django 4.2.10 on 2024-03-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_contactform_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
