# Generated by Django 4.2.10 on 2024-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("products", "0002_product_image_url_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="user_wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="user_wishlist", to="profiles.userprofile"
            ),
        ),
    ]
