# Generated by Django 4.2.10 on 2024-03-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
